name: taste_tube
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.3+3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  go_router: ^14.3.0
  font_awesome_flutter: ^10.7.0
  flutter_bloc: ^8.1.6
  intl_phone_field: ^3.2.0
  get_it: ^8.0.0
  http: ^1.2.2
  fpdart: ^1.1.0
  logger: ^2.4.0
  fluttertoast: ^8.2.8
  shared_preferences: ^2.2.3
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Ganh
      fonts:
        - asset: assets/fonts/Ganh/Ganh-Regular.otf
          style: normal
        - asset: assets/fonts/Ganh/Ganh-RegularItalic.otf
          style: italic
        - asset: assets/fonts/Ganh/Ganh-Thin.otf
          weight: 100
        - asset: assets/fonts/Ganh/Ganh-ThinItalic.otf
          style: italic
          weight: 100
