name: taste_tube
description: "A new Flutter project."

publish_to: "none"

version: 1.4.2+25

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.3.0
  flutter_bloc: ^9.0.0
  get_it: ^8.0.0
  fpdart: ^1.1.0
  logger: ^2.4.0
  fluttertoast: ^8.2.8
  shared_preferences: ^2.2.3
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.2.2
  dio: ^5.7.0
  package_info_plus: ^8.3.0
  font_awesome_flutter: ^10.7.0
  animated_toggle_switch: ^0.8.3
  flutter_slidable: ^4.0.0
  visibility_detector: ^0.4.0+2
  provider: ^6.1.2
  flutter_credit_card: ^4.1.0
  fl_chart: ^0.70.2
  animated_bottom_navigation_bar: ^1.4.0
  responsive_builder: ^0.7.1
  camera: ^0.11.0+2
  video_player: ^2.9.2
  get_thumbnail_video: ^0.7.3
  image_picker: ^1.1.2
  file_picker: ^8.3.7
  path_provider: ^2.1.4
  gallery_saver_plus: ^3.2.4
  cached_network_image: ^3.3.1
  better_player_plus: ^1.0.8
  uuid: ^4.5.1
  flutter_facebook_auth: ^6.0.4
  google_sign_in: ^6.2.2
  firebase_core: ^3.4.0
  firebase_database: ^11.3.5
  firebase_messaging: ^15.2.5
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  place_picker_google:
    git:
      url: https://github.com/Killian0812/place_picker_google
      ref: 8e2ef7fe3eaa1f0efa1f6d9f112b4f8b927907d9
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5
  stream_chat_flutter: ^9.7.0
  socket_io_client: ^3.0.2
  intl: ^0.19.0
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  collection: ^1.18.0
  share_plus: ^10.1.4
  intl_phone_field: ^3.2.0
  flutter_local_notifications: ^19.1.0
  flutter_launcher_icons: ^0.14.3
  emoji_picker_flutter: ^4.3.0
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5
  video_player_web_hls: ^1.3.0
  country_flags: ^3.2.0
  animate_do: ^4.2.0
  flutter_otp_text_field: ^1.5.1+1

dependency_overrides:
  video_player_android: 2.7.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

  fonts:
    - family: Ganh
      fonts:
        - asset: assets/fonts/Ganh/Ganh-Regular.otf
          style: normal
        - asset: assets/fonts/Ganh/Ganh-RegularItalic.otf
          style: italic
        - asset: assets/fonts/Ganh/Ganh-Thin.otf
          weight: 100
        - asset: assets/fonts/Ganh/Ganh-ThinItalic.otf
          style: italic
          weight: 100

flutter_localizations:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  supported-locales:
    - en
    - vi

flutter_native_splash:
  color: "#000000"
  image: assets/images/tastetube_inverted.png
  android: true
  ios: true
  web: true
