name: taste_tube
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.4+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  go_router: ^14.3.0
  font_awesome_flutter: ^10.7.0
  flutter_bloc: ^9.0.0
  intl_phone_field: ^3.2.0
  get_it: ^8.0.0
  fpdart: ^1.1.0
  logger: ^2.4.0
  fluttertoast: ^8.2.8
  shared_preferences: ^2.2.3
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.2.2
  dio: ^5.7.0
  camera: ^0.11.0+2
  video_player: ^2.9.2
  get_thumbnail_video: ^0.7.3
  image_picker: ^1.1.2
  file_picker: ^9.0.2
  path_provider: ^2.1.4
  uuid: ^4.5.1
  flutter_facebook_auth: ^6.0.4
  google_sign_in: ^6.2.2
  intl: ^0.19.0
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  animated_toggle_switch: ^0.8.3
  collection: ^1.18.0
  flutter_slidable: ^4.0.0
  cached_network_image: ^3.3.1
  visibility_detector: ^0.4.0+2
  provider: ^6.1.2
  better_player_plus: ^1.0.8
  gallery_saver_plus: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Ganh
      fonts:
        - asset: assets/fonts/Ganh/Ganh-Regular.otf
          style: normal
        - asset: assets/fonts/Ganh/Ganh-RegularItalic.otf
          style: italic
        - asset: assets/fonts/Ganh/Ganh-Thin.otf
          weight: 100
        - asset: assets/fonts/Ganh/Ganh-ThinItalic.otf
          style: italic
          weight: 100
