// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMv4uzsp7IEL-fsJYnIDC6SIkHSel5638',
    appId: '1:885591194987:web:7c557b8dc5a002ef91a02e',
    messagingSenderId: '885591194987',
    projectId: 'taste-tube',
    authDomain: 'taste-tube.firebaseapp.com',
    databaseURL: 'https://taste-tube-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taste-tube.appspot.com',
    measurementId: 'G-0FCFRS81KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-9rF-Ry_NDZ-Qs_tWy2icF8_sBDrmqG8',
    appId: '1:885591194987:android:5fed3c71f85631e091a02e',
    messagingSenderId: '885591194987',
    projectId: 'taste-tube',
    databaseURL: 'https://taste-tube-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taste-tube.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfJ1HyKeTGunco_uIiqR0KnAhLOxPFXX4',
    appId: '1:885591194987:ios:6c96cada4373feaf91a02e',
    messagingSenderId: '885591194987',
    projectId: 'taste-tube',
    databaseURL: 'https://taste-tube-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taste-tube.appspot.com',
    androidClientId: '885591194987-2dg97ho4pa226jqiq3gk5flebv4kgidd.apps.googleusercontent.com',
    iosClientId: '885591194987-h2h2ulqop54v0lilfk618q3iun38et1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasteTube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfJ1HyKeTGunco_uIiqR0KnAhLOxPFXX4',
    appId: '1:885591194987:ios:6c96cada4373feaf91a02e',
    messagingSenderId: '885591194987',
    projectId: 'taste-tube',
    databaseURL: 'https://taste-tube-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taste-tube.appspot.com',
    androidClientId: '885591194987-2dg97ho4pa226jqiq3gk5flebv4kgidd.apps.googleusercontent.com',
    iosClientId: '885591194987-h2h2ulqop54v0lilfk618q3iun38et1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasteTube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdIf20txQEAzmfkTCQtX3uJqqTClB2P4A',
    appId: '1:885591194987:web:ed75b290137b1b5691a02e',
    messagingSenderId: '885591194987',
    projectId: 'taste-tube',
    authDomain: 'taste-tube.firebaseapp.com',
    databaseURL: 'https://taste-tube-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taste-tube.appspot.com',
    measurementId: 'G-WXMG93LDXC',
  );

}